In [89]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [90]:
df = pd.read_csv('train.txt', sep=';',header=None,names=['text','emotion'])

In [91]:
df.shape

(16000, 2)

In [92]:
df.head()

,text,emotion
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger


In [93]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [94]:
df.drop_duplicates()

,text,emotion
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger
...,...,...
15995,i just had a very brief time in the beanbag an...,sadness
15996,i am now turning and i feel pathetic that i am...,sadness
15997,i feel strong and good overall,joy
15998,i feel like this was such a rude comment and i...,anger


In [95]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [96]:
unique_emotions = df['emotion'].unique() 
i =0
emotion_numbers = {}
for emotion in unique_emotions: 
    emotion_numbers[emotion]=i
    i+=1

In [97]:
print(emotion_numbers)

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}


# 1. Convert everyting to lower case 

In [98]:
df['text'] = df['text'].apply(lambda x : x.lower())


# 2. Remove punctuation (not req in ML can be used in DL)

In [99]:
import string 

def remove_punc(txt): 
    return txt.translate(str.maketrans('','',string.punctuation))

In [100]:
df['text'] = df['text'].apply(remove_punc)

# 3. Remove numbers

In [101]:
def remove_nums(txt): 
    new = ""
    for i in txt:
        if not i.isdigit(): 
            new = new + i
    return new

In [102]:
df['text'] = df['text'].apply(remove_nums)

# 4. Remove URLs/Links

# 5. Remove HTML tags (if data is scrapped)

# 6. Remove Emojis & Special characters

In [103]:
def remove_emojis(txt): 
    new = ""
    for i in txt:
        if i.isascii(): 
            new = new + i
    return new

df['text'] = df['text'].apply(remove_emojis)

# 7. Remove stop keywords: "is", "was", "and", "in" (not req in ML can be used in DL)

In [104]:
import nltk

In [105]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [106]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/shikshakkumar/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/shikshakkumar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [107]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [108]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [109]:
def remove_stopwords(txt): 
    words = txt.split() # do this if word_tokenize not working
    cleaned = []
    for i in words: 
        if not i in stop_words: 
            cleaned.append(i)
    return ' '.join(cleaned)

In [110]:
df['text'] = df['text'].apply(remove_stopwords)

In [111]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [112]:
from sklearn.feature_extraction.text import CountVectorizer 

documents = [
    "I love pizza", 
    "Pizza is the best", 
    "I love pasta", 
    "Pasta is great"
]

vectorizer = CountVectorizer() 

X = vectorizer.fit_transform(documents)

print("Vocabulary: ",vectorizer.get_feature_names_out())
print("\nBoW Matrxix:\n", X.toarray()) # Bag Of Words 

Vocabulary:  ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

BoW Matrxix:
 [[0 0 0 1 0 1 0]
 [1 0 1 0 0 1 1]
 [0 0 0 1 1 0 0]
 [0 1 1 0 1 0 0]]


In [113]:
vectorizer = CountVectorizer(ngram_range=(1,2)) 

X = vectorizer.fit_transform(documents)

print("Vocabulary: ",vectorizer.get_feature_names_out())
print("\nBoW Matrxix:\n", X.toarray()) # Bag Of Words 

Vocabulary:  ['best' 'great' 'is' 'is great' 'is the' 'love' 'love pasta' 'love pizza'
 'pasta' 'pasta is' 'pizza' 'pizza is' 'the' 'the best']

BoW Matrxix:
 [[0 0 0 0 0 1 0 1 0 0 1 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 1 1 0 0 0 0]]


In [114]:
vectorizer = CountVectorizer(ngram_range=(3,3)) 

X = vectorizer.fit_transform(documents)

print("Vocabulary: ",vectorizer.get_feature_names_out())
print("\nBoW Matrxix:\n", X.toarray()) # Bag Of Words 

Vocabulary:  ['is the best' 'pasta is great' 'pizza is the']

BoW Matrxix:
 [[0 0 0]
 [1 0 1]
 [0 0 0]
 [0 1 0]]


In [115]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "I love pizza", 
    "Pizza is the best", 
    "I love pasta", 
    "Pasta is great"
]

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(documents)

print("Vocabulary: ",vectorizer.get_feature_names_out())
print("\nBoW Matrxix:\n", X.toarray()) # Bag Of Words 

Vocabulary:  ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

BoW Matrxix:
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]


# Apply everything on dataset

In [130]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [131]:
df.shape

(16000, 2)

In [132]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

bow_vectorizer = CountVectorizer()

X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [133]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score


nb_model = MultinomialNB()

nb_model.fit(X_train_bow,y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [134]:
predict_bow = nb_model.predict(X_test_bow)
print("Accuracy: ", accuracy_score(y_test,predict_bow))

Accuracy:  0.768125


In [135]:
predict_bow

array(['sadness', 'joy', 'sadness', ..., 'joy', 'joy', 'sadness'],
      shape=(3200,), dtype='<U8')

In [136]:
tfid_vectorizer = TfidfVectorizer()

X_train_tfid = tfid_vectorizer.fit_transform(X_train)
X_test_tfid = tfid_vectorizer.transform(X_test)

nb2_model = MultinomialNB()

nb2_model.fit(X_train_tfid,y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [137]:
predict_tfid = nb2_model.predict(X_test_bow)
print("Accuracy: ", accuracy_score(y_test,predict_tfid))

Accuracy:  0.6753125


In [139]:
from sklearn.linear_model import LogisticRegression
     
logistic_model = LogisticRegression(max_iter=1000)
     
logistic_model.fit(X_train_tfid,y_train)
     

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [141]:
log_pred = logistic_model.predict(X_test_tfid)
print(accuracy_score(y_test,log_pred ))

0.8628125


In [142]:
X_train_tfid

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 116059 stored elements and shape (12800, 13361)>